### ISSUE TITLE
Remove insecure MD5 from documentation

### ISSUE THREAD

**Issue by PremyslFiala** [zendframework/zend-authentication#13]
It tears my soul that documentation about authentication mentions md5 so much.
There is even an example how to use Autheticatin with md5.
MD5 is insecure and todays RDBS support newer and secure methods....
(There is also md5 note in code comments)

https://docs.zendframework.com/zend-authentication/adapter/dbtable/credential-treatment/

**Comment by weierophinney** [comment]
Much of this documentation dates as far back as 2007. Due to the amount of documentation in the project, we rarely go back and review for content unless a volunteer or contributor decides to do so.

As such, we would welcome pull requests to improve this documentation, if you are so inclined.
