### ISSUE TITLE
Installation with composer produced InvalidArgumentException

### ISSUE THREAD

**Issue by ghost** [zendframework/zend-authentication#15]
Attempted composer require zendframework/zend-authentication on the latest zf3 framework. Produced the following error:

[InvalidArgumentException]  
  Could not find package require at any version for your minimum-stability (d  
  ev). Check the package spelling or your minimum-stability

**Comment by ezimuel** [comment]
@Farsideman the only requirement for `zend-authentication` is `zend-stdlib` ver 2.7+ (including ver 3) as reported in [composer.json](https://github.com/zendframework/zend-authentication/blob/master/composer.json#L17). That means with ZF3 it works just fine.
Maybe you have some issue with your `composer.json`. For instance, do you have:
`"minimum-stability": "dev"` ?

**Comment by ghost** [comment]
Thank you for getting back to me so quickly. My ZF3 installation is as per the tutorials without modification. I have completed both the Album and Blog tutorials with success and as indicated, in my first post, the minimum-stability is "dev". Confirmed by the composer.phar development-status command. Composer also reports "Using version ^3.0 for zendframework/zend-stdlib". I did, however, install zend-authentication using composer.json without issues.

**Comment by ghost** [comment]
Further to this conversation, when I attempted to enable zend\authentication in modules.config.php, I encountered the following error:

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (zend\authentication) could not be initialized.' in /Applications/MAMP/htdocs/gsscc/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 203

Zend\ModuleManager\Exception\RuntimeException: Module (Authentication) could not be initialized. in /Applications/MAMP/htdocs/gsscc/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 203

Can you point me to a good tutorial using the Callback Verification adapter? Perhaps I am missing something obvious.

**Comment by ghost** [comment]
Here is my composer.json:

```json
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for Zend Framework zend-mvc applications",
    "type": "project",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "mvc",
        "zf"
    ],
    "homepage": "http://framework.zend.com/",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "^5.6 || ^7.0",
        "zendframework/zend-component-installer": "^1.0 || ^0.3 || ^1.0.0-dev@dev",
        "zendframework/zend-mvc": "^3.0.1",
        "zfcampus/zf-development-mode": "^3.0",
        "zendframework/zend-db": "^2.8.1",
        "zendframework/zend-mvc-form": "^1.0",
        "zendframework/zend-navigation": "^2.8",
        "zendframework/zend-paginator": "^2.7",
        "zendframework/zend-mvc-i18n": "^1.0",
        "zendframework/zend-session": "^2.7",
        "zendframework/zend-cache": "^2.7",
        "zendframework/zend-authentication": "^2.5.3",
        "zendframework/zend-stdlib": "^3.0"
    },
    "autoload": {
        "psr-4": {
            "Application\": "module/Application/src/",
            "Album\": "module/Album/src/",
            "Auth\": "module/Auth/src/",
            "Blank\": "module/Blank/src/",
            "Blog\": "module/Blog/src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "ApplicationTest\": "module/Application/test/",
            "AlbumTest\": "module/Album/test/"
        }
    },
    "extra": [],
    "scripts": {
        "cs-check": "phpcs",
        "cs-fix": "phpcbf",
        "development-disable": "zf-development-mode disable",
        "development-enable": "zf-development-mode enable",
        "development-status": "zf-development-mode status",
        "post-create-project-cmd": [
            "@development-enable"
        ],
        "serve": "php -S 0.0.0.0:8080 -t public/ public/index.php",
        "test": "phpunit"
    },
    "require-dev": {
        "zendframework/zend-test": "^3.0"
    }
}
```

**Comment by ghost** [comment]
Here is my modules.config.php:

```php
return [
    'Zend\Authentication',
    'Zend\Cache',       // Not implemented
    'Zend\Session',     // Not implemented
    'Zend\Mvc\I18n',    // Not implemented
    'Zend\Paginator',   // Implemented in Album
    'Zend\Navigation',  // Implemented in Album
    'Zend\Form',        // Implemented in Album, Blog
    'Zend\Db',
    'Zend\Router',
    'Zend\Validator',
    'Application',
    'Album',            // Tutorial with navigation, breadcrumbs, and pagination
    'Auth',              // Empty module
    'Blog',             // Tutorial
];
```

**Comment by bhupinderdeol** [comment]
below section may require 
"psr-4": {
"Application": "module/Application/src/",
"Album": "module/Album/src/",
"Auth": "module/Auth/src/",
"Blank": "module/Blank/src/",
"Blog": "module/Blog/src/"
}
},
"autoload-dev": {
"psr-4": {
"ApplicationTest": "module/Application/test/",
"AlbumTest": "module/Album/test/"
}

_______________________________may this chages but backup not my responsibilty
"autoload": {
"psr-4": {
"Application\\": "module/Application/src/",
"Album\\": "module/Album/src/",
"Auth\\": "module/Auth/src/",
"Blank\\": "module/Blank/src/",
"Blog\\": "module/Blog/src/"
}
},
"autoload-dev": {
"psr-4": {
"ApplicationTest\\": "module/Application/test/",
"AlbumTest\\": "module/Album/test/"
}
},

**Comment by Xerkus** [comment]
Could not reproduce. Most likely minimum php version requirement is not met on user side.

For support please use our [Slack chat](https://zendframework-slack.herokuapp.com/) and [forums](https://discourse.zendframework.com/)
