### ISSUE TITLE
ZF3 - Using Identity view helper requires that 'Zend\Authentication\AuthenticationService' be registered

### ISSUE THREAD

**Issue by olegkrivtsov** [zendframework/zend-authentication#17]
When using `zend-authentication` with ZF3, it seems that `identity` view helper requires that you register `Zend\Authentication\AuthenticationService` (literally) in your config file:

```
'service_manager' => [
        'factories' => [
            'Zend\Authentication\AuthenticationService' => Service\Factory\AuthenticationServiceFactory::class,
        ],
    ],
```

But, I expect that I should register this service with the `::class` keyword, as follows:

```
'service_manager' => [
        'factories' => [
            Zend\Authentication\AuthenticationService::class => Service\Factory\AuthenticationServiceFactory::class,
        ],
    ],
```

However, this doesn't work. Is this a bug?

**Comment by weierophinney** [comment]
@olegkrivtsov It looks like you are declaring a namespace in your configuration file (based on the fact that you are declaring your factory using `Service\Factory\AuthenticatinoServiceFactory::class`. As such, try globally qualifying the `AuthenticationService` class:

``` php
'service_manager' => [
    'factories' => [
        // Note the "\" preceding the "Z"!
        \Zend\Authentication\AuthenticationService::class => Service\Factory\AuthenticationServiceFactory::class,
    ],
],
```

**Comment by olegkrivtsov** [comment]
@weierophinney it works. Thanks. This can be closed.
