### ISSUE TITLE
Add PHP 7.2 support

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-authentication#33]
* Update Travis configuration
* Check Travis results

**Comment by michalbundyra** [comment]
@froschdesign check #30, almost everything is done there, we just need add 7.2 in travis ci matrix.

**Comment by froschdesign** [comment]
@webimpress 
> we just need add 7.2 in travis ci matrix

This includes the 7.2 support! 😉

**Comment by michalbundyra** [comment]
@froschdesign 
Yeah, but "drop HHVM" is done in #30, so it's difficult to work on this issue once #30 contains many changes in Travis configuration. Definitely then it will be conflicted !

**Comment by froschdesign** [comment]
@webimpress 
#30 is already in the project: https://github.com/orgs/zendframework/projects/3

**Comment by michalbundyra** [comment]
@froschdesign 
> #30 is already in the project: https://github.com/orgs/zendframework/projects/3

Sorry, I can't see it.

**Comment by froschdesign** [comment]
@webimpress 
> Sorry, I can't see it.

Sh*t! :weary:
(Okay, I have a plan. Please have some patience.)

**Comment by weierophinney** [comment]
Fixed with #34; will release with 2.6.0.
